bash -> sh; removing sudo requirement

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # This script is meant for quick & easy install via:
 # `sudo curl -sSL https://raw.githubusercontent.com/ContainerSolutions/minimesos/master/bin/install | bash`
@@ -6,40 +6,39 @@
 # Uses the latest release, unless a version identifier is specified as a parameter of this script.
 
 command_exists() {
-	command -v "$@" > /dev/null 2>&1
+    command -v "$@" > /dev/null 2>&1
 }
 
 install_version() {
-    echo "Using $1 to install minimesos $2"
-    curl -sSL $1 | bash -s $2
+    echo "Using $1"
+    curl -sSL $1 | sh -s $2
 }
 
 if ! command_exists curl; then
-	echo "Please install curl to fetch the minimesos files"
-	exit 1
+    echo "Please install curl to fetch the minimesos files"
+    exit 1
 fi
 
 VERSION=$(echo $@ | xargs)
 
 if [ -z "$VERSION" ]; then
-	MAVEN_METADATA=$(curl -s https://jitpack.io/com/github/ContainerSolutions/minimesos/maven-metadata.xml)
-	VERSION=$(echo "$MAVEN_METADATA" | awk -F '[<>]' '/release/{print $3}')
-	if [ ! "$VERSION" ]; then
-		echo "Cannot determine latest release of minimesos"
-		exit 1
-	fi
+    MAVEN_METADATA=$(curl -s https://jitpack.io/com/github/ContainerSolutions/minimesos/maven-metadata.xml)
+    VERSION=$(echo "$MAVEN_METADATA" | awk -F '[<>]' '/release/{print $3}')
+    if [ ! "$VERSION" ]; then
+	echo "Cannot determine latest release of minimesos"
+	exit 1
+    fi
 fi
-
-curl -sSL -X HEAD https://jitpack.io/com/github/ContainerSolutions/minimesos/$VERSION/pom
 
 # invoking versioned installation script
 echo "Installing minimesos $VERSION"
 SCRIPT_PATH=https://raw.githubusercontent.com/ContainerSolutions/minimesos/$VERSION
 httpcode=$(curl -s -o /dev/null -I -w '%{http_code}' --max-time 1 $SCRIPT_PATH/bin/install-version || echo "404" )
 if [ $httpcode -eq 200 ]; then
-	install_version $SCRIPT_PATH/bin/install-version $VERSION
+    install_version $SCRIPT_PATH/bin/install-version $VERSION
 else
     # initial version of minimesos used single install script
+    # FIXME: this will only skip guessing the latest version and will try to pull the same "install-version" that failed above
     install_version $SCRIPT_PATH/bin/install $VERSION
 fi
 
